/**
 * Generate the draft-free client taxonomy file from the authored corpus.
 *
 * Reads the full ICD-11 Chapter 6 corpus (`icd11Conditions`, which carries the authored
 * definition drafts) and emits `src/data/conditions/taxonomy.ts` containing ONLY the
 * factual taxonomy fields (slug, name, icd11_code, icd11_grouping, provenance). The four
 * definition fields are deliberately dropped so that no unverified draft text can ever
 * reach the anon client bundle — drafts live exclusively in the DB (gated by RLS + the
 * conditions_public masking view).
 *
 * This is a DEV TOOL. It imports the drafts, but its OUTPUT (taxonomy.ts) does not, and
 * the corpus modules it reads are imported only by scripts — never by client code.
 *
 * Usage:
 *   npx tsx src/scripts/generateConditionsTaxonomy.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { icd11Conditions } from '@/data/conditions/icd11Chapter6';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUT = path.resolve(__dirname, '../data/conditions/taxonomy.ts');

/** Escape a string for emission inside a single-quoted TS literal. */
function q(value: string): string {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

const rows = icd11Conditions
    .map((c) => `    { slug: ${q(c.slug)}, name: ${q(c.name)}, icd11_code: ${q(c.icd11_code)}, icd11_grouping: ${q(c.icd11_grouping)}, provenance: ${q(c.provenance)} },`)
    .join('\n');

const file = `/**
 * AUTO-GENERATED by src/scripts/generateConditionsTaxonomy.ts — do not edit by hand.
 *
 * Draft-free taxonomy for all ${icd11Conditions.length} ICD-11 Chapter 6 conditions: only the factual
 * reference fields (slug, name, icd11_code, icd11_grouping, provenance). The four
 * plain-language DEFINITION fields are intentionally absent — they live ONLY in the DB,
 * gated by RLS and the conditions_public masking view, and must never ship to the anon
 * bundle. This file is the client fallback used when the conditions_public view is
 * unreachable; every row is unverified with null definitions, so it can render the
 * taxonomy A–Z without exposing any clinical copy.
 *
 * Regenerate with: npx tsx src/scripts/generateConditionsTaxonomy.ts
 */

import type { Condition } from '@/types/condition';
import { icd11GroupingToTopGroup } from './taxonomyGroup';

interface TaxonomyRow {
    slug: string;
    name: string;
    icd11_code: string;
    icd11_grouping: string;
    provenance: string;
}

const ROWS: TaxonomyRow[] = [
${rows}
];

/** All conditions as taxonomy-only \`Condition\` rows — definitions null, unverified. */
export const conditionsTaxonomy: Condition[] = ROWS.map((r) => ({
    slug: r.slug,
    name: r.name,
    icd11_code: r.icd11_code,
    icd11_grouping: r.icd11_grouping,
    taxonomy_group: icd11GroupingToTopGroup(r.icd11_grouping),
    related_category_slug: null,
    short_definition: null,
    what_it_feels_like: null,
    how_it_differs: null,
    when_more_than_everyday: null,
    crisis_flag: false,
    provenance: r.provenance,
    verification_status: 'unverified',
    reading_level: '8th grade',
}));
`;

fs.writeFileSync(OUT, file, 'utf-8');
console.log(`✅ Wrote ${OUT} — ${icd11Conditions.length} taxonomy rows (no definition text).`);
