// Clarity Journal V2 — Therapist Summary Report PDF Generator
// Client-side PDF generation using jsPDF
// Produces a clean, professional report a therapist would actually want to receive

import type { ReportConfig, ReportData } from '../types';
import { formatDate, formatDateRange } from '../dates';

const TEAL = [26, 155, 140] as const;     // #1A9B8C
const CHARCOAL = [26, 26, 46] as const;   // #1A1A2E
const GRAY = [100, 116, 139] as const;    // #64748B
const LIGHT_GRAY = [241, 245, 249] as const; // #F1F5F9
const RED = [220, 38, 38] as const;       // #DC2626
const AMBER = [245, 158, 11] as const;    // #F59E0B
const GREEN = [16, 185, 129] as const;    // #10B981

const DISCLAIMER = 'This report is generated from a self-directed educational wellness tool (Psychage). It is not a clinical assessment, diagnosis, or medical record. The data reflects the user\'s self-reported experiences and should be interpreted in clinical context by a licensed professional.';
const FOOTER_TEXT = 'Generated via Psychage (psychage.com). For educational purposes only.';

export async function generateTherapistReportPDF(
  reportData: ReportData,
  config: ReportConfig,
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const m = 18; // margin
  const cw = pw - m * 2; // content width
  let y = m;
  let pageNum = 1;

  // ── Helpers ──

  const setColor = (rgb: readonly [number, number, number]) => doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  const setFillColor = (rgb: readonly [number, number, number]) => doc.setFillColor(rgb[0], rgb[1], rgb[2]);

  const addFooter = () => {
    doc.setFontSize(7);
    setColor(GRAY);
    doc.setFont('helvetica', 'normal');
    doc.text(FOOTER_TEXT, m, ph - 8);
    doc.text(`Page ${pageNum}`, pw - m, ph - 8, { align: 'right' });
  };

  const newPage = () => {
    addFooter();
    doc.addPage();
    pageNum++;
    y = m;
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > ph - 15) newPage();
  };

  const drawSectionHeader = (title: string) => {
    ensureSpace(15);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    setColor(TEAL);
    doc.text(title, m, y);
    y += 2;
    doc.setDrawColor(TEAL[0], TEAL[1], TEAL[2]);
    doc.setLineWidth(0.5);
    doc.line(m, y, m + cw, y);
    y += 7;
    setColor(CHARCOAL);
  };

  const drawSubheader = (title: string) => {
    ensureSpace(10);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    setColor(CHARCOAL);
    doc.text(title, m, y);
    y += 5;
  };

  const drawParagraph = (text: string, fontSize = 9) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', 'normal');
    setColor(CHARCOAL);
    const lines = doc.splitTextToSize(text, cw);
    ensureSpace(lines.length * 4 + 2);
    doc.text(lines, m, y);
    y += lines.length * 4 + 2;
  };

  const drawMetricRow = (label: string, value: string, highlight = false) => {
    ensureSpace(7);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(GRAY);
    doc.text(label, m + 4, y);
    doc.setFont('helvetica', 'bold');
    if (highlight) setColor(TEAL);
    else setColor(CHARCOAL);
    doc.text(value, pw - m, y, { align: 'right' });
    y += 6;
  };

  const trendArrow = (trend: string): string => {
    if (trend === 'improving') return '↑ Improving';
    if (trend === 'declining' || trend === 'worsening') return '↓ Declining';
    return '→ Stable';
  };

  // ══════════════════════════════════════════════════
  // PAGE 1: COVER / AT-A-GLANCE SUMMARY
  // ══════════════════════════════════════════════════

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  setColor(TEAL);
  doc.text('Clarity Journal', pw / 2, y + 5, { align: 'center' });
  y += 10;
  doc.setFontSize(13);
  setColor(CHARCOAL);
  doc.text('Wellness Summary Report', pw / 2, y, { align: 'center' });
  y += 6;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(GRAY);
  doc.text(`Generated by ${config.clientName || 'Client'} using Psychage`, pw / 2, y, { align: 'center' });
  y += 10;

  // Period & info
  doc.setDrawColor(200, 200, 200);
  doc.line(m, y, pw - m, y);
  y += 6;

  doc.setFontSize(9);
  setColor(CHARCOAL);
  doc.setFont('helvetica', 'bold');
  doc.text('Reporting Period:', m, y);
  doc.setFont('helvetica', 'normal');
  doc.text(formatDateRange(config.periodStart, config.periodEnd), m + 38, y);

  if (config.therapistName) {
    doc.setFont('helvetica', 'bold');
    doc.text('Therapist:', pw / 2, y);
    doc.setFont('helvetica', 'normal');
    doc.text(config.therapistName, pw / 2 + 22, y);
  }
  y += 5;

  if (config.nextSessionDate) {
    doc.setFont('helvetica', 'bold');
    doc.text('Next Session:', m, y);
    doc.setFont('helvetica', 'normal');
    doc.text(formatDate(config.nextSessionDate), m + 30, y);
    y += 5;
  }
  y += 4;

  // Disclaimer box
  setFillColor(LIGHT_GRAY);
  const disclaimerLines = doc.splitTextToSize(DISCLAIMER, cw - 10);
  const disclaimerHeight = disclaimerLines.length * 3.5 + 8;
  doc.roundedRect(m, y, cw, disclaimerHeight, 2, 2, 'F');
  doc.setFontSize(7.5);
  setColor(GRAY);
  doc.text(disclaimerLines, m + 5, y + 5);
  y += disclaimerHeight + 8;

  // At-a-Glance metrics
  drawSectionHeader('At a Glance');

  drawMetricRow('Overall Mood (avg)', `${reportData.mood.averageMood}/10  ${trendArrow(reportData.mood.moodTrend)}`, true);
  drawMetricRow('Journal Days', `${reportData.journalDays} days`);
  drawMetricRow('Total Entries', `${reportData.totalEntries}`);

  if (reportData.screeners.phq2.length > 0) {
    const latestPHQ = reportData.screeners.phq2[reportData.screeners.phq2.length - 1];
    drawMetricRow('PHQ-2 (latest)', `${latestPHQ.score}/6  ${trendArrow(reportData.screeners.phq2Trend)}`);
  }
  if (reportData.screeners.gad2.length > 0) {
    const latestGAD = reportData.screeners.gad2[reportData.screeners.gad2.length - 1];
    drawMetricRow('GAD-2 (latest)', `${latestGAD.score}/6  ${trendArrow(reportData.screeners.gad2Trend)}`);
  }

  drawMetricRow('Coping Tools Used', `${reportData.coping.toolUsage.length} tools`);
  drawMetricRow('Safety Flags', reportData.safety.hasFlags ? `${reportData.safety.flags.length} flagged` : 'None');

  // ══════════════════════════════════════════════════
  // PAGE 2: MOOD & EMOTION PATTERNS
  // ══════════════════════════════════════════════════

  if (config.includeSections.moodTrends) {
    newPage();
    drawSectionHeader('Mood & Emotion Patterns');

    // Mood trend chart (simple text-based representation for PDF)
    if (reportData.mood.dailyAverages.length > 0) {
      drawSubheader('Daily Mood Trend');

      // Draw a simple bar-chart representation
      const maxBarWidth = cw - 40;
      for (const day of reportData.mood.dailyAverages.slice(-14)) {
        ensureSpace(6);
        doc.setFontSize(7);
        setColor(GRAY);
        doc.text(day.date.slice(5), m, y); // MM-DD
        const barWidth = (day.avg / 10) * maxBarWidth;
        const barColor = day.avg >= 7 ? GREEN : day.avg >= 4 ? AMBER : RED;
        setFillColor(barColor);
        doc.roundedRect(m + 18, y - 3, barWidth, 4, 1, 1, 'F');
        doc.setFontSize(7);
        setColor(CHARCOAL);
        doc.text(day.avg.toFixed(1), m + 20 + barWidth + 2, y);
        y += 5.5;
      }
      y += 4;
    }

    // Time of day comparison
    if (reportData.mood.morningAvg !== null || reportData.mood.eveningAvg !== null) {
      drawSubheader('Time of Day');
      if (reportData.mood.morningAvg !== null) drawMetricRow('Morning Average', `${reportData.mood.morningAvg}/10`);
      if (reportData.mood.eveningAvg !== null) drawMetricRow('Evening Average', `${reportData.mood.eveningAvg}/10`);
      y += 2;
    }

    // Top emotions
    if (reportData.mood.topEmotions.length > 0) {
      drawSubheader('Most Frequent Emotions');
      for (const em of reportData.mood.topEmotions) {
        drawMetricRow(`${em.name} (${em.category})`, `${em.count}x, avg intensity ${em.avgIntensity}%`);
      }
      y += 2;
    }

    // Narrative summary
    const moodNarrative = generateMoodNarrative(reportData);
    if (moodNarrative) {
      drawSubheader('Summary');
      drawParagraph(moodNarrative);
    }
  }

  // ══════════════════════════════════════════════════
  // PAGE 3: VALIDATED SCREENER SCORES
  // ══════════════════════════════════════════════════

  if (config.includeSections.screenerScores && reportData.screeners.phq2.length > 0) {
    newPage();
    drawSectionHeader('Validated Screener Scores');

    // PHQ-2
    if (reportData.screeners.phq2.length > 0) {
      drawSubheader('Depression Screen — PHQ-2 (Kroenke et al., 2003)');
      doc.setFontSize(8);
      setColor(GRAY);
      doc.text('Range: 0-6. Score ≥3 suggests a positive depression screen. This is a screening result, not a diagnosis.', m, y);
      y += 5;

      for (const entry of reportData.screeners.phq2) {
        const level = entry.score >= 5 ? 'Elevated' : entry.score >= 3 ? 'Moderate' : 'Low';
        drawMetricRow(`Week of ${formatDate(entry.date)}`, `${entry.score}/6 — ${level}`);
      }
      y += 3;
    }

    // GAD-2
    if (reportData.screeners.gad2.length > 0) {
      drawSubheader('Anxiety Screen — GAD-2 (Kroenke et al., 2007)');
      doc.setFontSize(8);
      setColor(GRAY);
      doc.text('Range: 0-6. Score ≥3 suggests a positive anxiety screen. This is a screening result, not a diagnosis.', m, y);
      y += 5;

      for (const entry of reportData.screeners.gad2) {
        const level = entry.score >= 5 ? 'Elevated' : entry.score >= 3 ? 'Moderate' : 'Low';
        drawMetricRow(`Week of ${formatDate(entry.date)}`, `${entry.score}/6 — ${level}`);
      }
      y += 3;
    }

    // PSS-4
    if (reportData.screeners.pss4.length > 0) {
      drawSubheader('Stress Check — PSS-4 (Cohen et al., 1983)');
      for (const entry of reportData.screeners.pss4) {
        drawMetricRow(`Week of ${formatDate(entry.date)}`, `${entry.score}/8`);
      }
      y += 3;
    }

    // WHO-5
    if (reportData.screeners.who5.length > 0) {
      drawSubheader('Well-being — WHO-5 (WHO, 1998)');
      for (const entry of reportData.screeners.who5) {
        drawMetricRow(`Week of ${formatDate(entry.date)}`, `${entry.score}/10`);
      }
    }
  }

  // ══════════════════════════════════════════════════
  // PAGE 4: BEHAVIORAL, SLEEP & STRESSOR SUMMARY
  // ══════════════════════════════════════════════════

  if (config.includeSections.behavioralActivity || config.includeSections.sleepPatterns || config.includeSections.stressorSummary) {
    newPage();

    if (config.includeSections.behavioralActivity) {
      drawSectionHeader('Behavioral Activity');
      drawMetricRow('Avg Activity Level', `${reportData.behavioral.avgActivityLevel}/10`);
      drawMetricRow('Avg Enjoyment', `${reportData.behavioral.avgEnjoyment}/10`);
      drawMetricRow('Avg Mastery', `${reportData.behavioral.avgMastery}/10`);
      drawMetricRow('Social Interactions (daily avg)', `${reportData.behavioral.socialInteractionAvg}`);
      drawMetricRow('Days with No Activities Logged', `${reportData.behavioral.zeroDays}`);

      if (reportData.behavioral.moodCorrelation !== null) {
        drawMetricRow('Activity-Mood Correlation', `r = ${reportData.behavioral.moodCorrelation}`);
      }

      if (Object.keys(reportData.behavioral.categoryDistribution).length > 0) {
        drawSubheader('Activity Categories');
        for (const [cat, count] of Object.entries(reportData.behavioral.categoryDistribution)) {
          drawMetricRow(cat.charAt(0).toUpperCase() + cat.slice(1), `${count} activities`);
        }
      }
      y += 4;
    }

    if (config.includeSections.sleepPatterns) {
      drawSectionHeader('Sleep Patterns');
      drawMetricRow('Avg Duration', `${reportData.sleep.avgDuration} hours`);
      drawMetricRow('Avg Quality', `${reportData.sleep.avgQuality}/10`);
      drawMetricRow('Consistency', `${reportData.sleep.consistencyScore}/10`);
      drawMetricRow('Nights Below 6 Hours', `${reportData.sleep.nightsBelow6}`);

      if (reportData.sleep.moodCorrelation !== null) {
        drawMetricRow('Sleep Quality-Mood Correlation', `r = ${reportData.sleep.moodCorrelation}`);
      }

      if (reportData.sleep.topFactors.length > 0) {
        drawSubheader('Contributing Factors');
        for (const f of reportData.sleep.topFactors) {
          drawMetricRow(f.factor.charAt(0).toUpperCase() + f.factor.slice(1), `${f.count} nights`);
        }
      }
      y += 4;
    }

    if (config.includeSections.stressorSummary) {
      drawSectionHeader('Stressors & Triggers');
      drawMetricRow('Recurring Stressors', `${reportData.stressors.recurringCount}`);

      if (reportData.stressors.topByFrequency.length > 0) {
        drawSubheader('Most Frequent');
        for (const s of reportData.stressors.topByFrequency.slice(0, 3)) {
          drawMetricRow(`${s.description} (${s.category})`, `${s.count}x`);
        }
      }

      if (reportData.stressors.topByIntensity.length > 0) {
        drawSubheader('Highest Intensity');
        for (const s of reportData.stressors.topByIntensity.slice(0, 3)) {
          drawMetricRow(`${s.description} (${s.category})`, `${s.avgIntensity}/10`);
        }
      }
    }
  }

  // ══════════════════════════════════════════════════
  // PAGE 5: THOUGHT RECORDS & COPING EFFECTIVENESS
  // ══════════════════════════════════════════════════

  if (config.includeSections.thoughtRecords || config.includeSections.copingEffectiveness) {
    newPage();

    if (config.includeSections.thoughtRecords) {
      drawSectionHeader('Thought Records');
      drawMetricRow('Records Completed', `${reportData.thoughtRecords.count}`);
      drawMetricRow('Completion Rate', `${Math.round(reportData.thoughtRecords.completionRate * 100)}%`);

      if (reportData.thoughtRecords.topDistortions.length > 0) {
        drawSubheader('Most Common Cognitive Distortions');
        for (const d of reportData.thoughtRecords.topDistortions) {
          drawMetricRow(d.name, `${d.count} occurrences`);
        }
      }
      y += 4;
    }

    if (config.includeSections.copingEffectiveness) {
      drawSectionHeader('Coping Strategy Effectiveness');

      if (reportData.coping.toolUsage.length > 0) {
        // Table header
        ensureSpace(10);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        setColor(GRAY);
        doc.text('Strategy', m + 4, y);
        doc.text('Uses', m + 70, y);
        doc.text('Avg Reduction', m + 90, y);
        y += 2;
        doc.setDrawColor(200, 200, 200);
        doc.line(m, y, pw - m, y);
        y += 4;

        doc.setFont('helvetica', 'normal');
        setColor(CHARCOAL);
        for (const tool of reportData.coping.toolUsage) {
          ensureSpace(6);
          doc.setFontSize(9);
          doc.text(tool.tool, m + 4, y);
          doc.text(`${tool.count}`, m + 70, y);
          const reductionText = tool.avgReduction > 0 ? `-${tool.avgReduction}` : `${tool.avgReduction}`;
          doc.text(reductionText, m + 90, y);
          y += 5.5;
        }
        y += 3;

        if (reportData.coping.mostEffective) {
          drawMetricRow('Most Effective', reportData.coping.mostEffective, true);
        }
        if (reportData.coping.leastEffective) {
          drawMetricRow('Least Effective', reportData.coping.leastEffective);
        }
      } else {
        drawParagraph('No coping tool usage was logged during this period.');
      }
    }
  }

  // ══════════════════════════════════════════════════
  // PAGE 6: FREE-FORM EXCERPTS (if included)
  // ══════════════════════════════════════════════════

  if (config.includeSections.freeFormExcerpts && reportData.freeFormExcerpts.length > 0) {
    newPage();
    drawSectionHeader('Journal Excerpts');
    drawParagraph('The following excerpts were selected by the client for inclusion in this report.', 8);
    y += 2;

    for (const excerpt of reportData.freeFormExcerpts) {
      ensureSpace(20);

      // Date header
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      setColor(TEAL);
      doc.text(formatDate(excerpt.date), m, y);
      y += 4;

      if (excerpt.prompt) {
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        setColor(GRAY);
        const promptLines = doc.splitTextToSize(`Prompt: "${excerpt.prompt}"`, cw - 8);
        doc.text(promptLines, m + 4, y);
        y += promptLines.length * 3.5 + 2;
      }

      // Quote content
      setFillColor(LIGHT_GRAY);
      const contentLines = doc.splitTextToSize(excerpt.content, cw - 16);
      const boxHeight = contentLines.length * 4 + 6;
      doc.roundedRect(m + 2, y - 2, cw - 4, boxHeight, 2, 2, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      setColor(CHARCOAL);
      doc.text(contentLines, m + 8, y + 2);
      y += boxHeight + 5;
    }
  }

  // ══════════════════════════════════════════════════
  // FINAL PAGE: SAFETY & SESSION PREPARATION
  // ══════════════════════════════════════════════════

  if (config.includeSections.safetyFlags || config.includeSections.sessionPrepPrompts) {
    newPage();

    if (config.includeSections.safetyFlags) {
      drawSectionHeader('Safety Summary');

      if (reportData.safety.hasFlags) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        setColor(RED);
        doc.text('Safety concerns were flagged during this period:', m, y);
        y += 6;

        doc.setFont('helvetica', 'normal');
        setColor(CHARCOAL);
        for (const flag of reportData.safety.flags) {
          ensureSpace(8);
          doc.setFontSize(9);
          doc.text(`• ${formatDate(flag.date)} — ${flag.details} (Source: ${flag.source})`, m + 4, y);
          y += 5;
        }
      } else {
        drawParagraph('No safety concerns were flagged during this reporting period.');
      }
      y += 6;
    }

    if (config.includeSections.sessionPrepPrompts) {
      drawSectionHeader('Session Preparation Prompts');
      drawParagraph('The following conversation starters are auto-generated based on the journaling data. They are suggestions, not clinical recommendations.', 8);
      y += 2;

      for (let i = 0; i < reportData.sessionPrompts.length; i++) {
        ensureSpace(12);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        setColor(CHARCOAL);
        const promptLines = doc.splitTextToSize(`${i + 1}. ${reportData.sessionPrompts[i]}`, cw - 10);
        doc.text(promptLines, m + 2, y);
        y += promptLines.length * 4 + 3;
      }
    }
  }

  // Final footer
  addFooter();

  // Save
  const dateStr = new Date().toISOString().slice(0, 10);
  const clientPart = config.clientName ? `-${config.clientName.replace(/\s+/g, '-').toLowerCase()}` : '';
  doc.save(`clarity-journal-report${clientPart}-${dateStr}.pdf`);
}

// ── Helper: Generate mood narrative ──

function generateMoodNarrative(data: ReportData): string {
  const parts: string[] = [];

  if (data.mood.dailyAverages.length > 0) {
    parts.push(`Over this ${data.journalDays}-day period, the average self-reported mood was ${data.mood.averageMood}/10.`);

    if (data.mood.moodTrend === 'improving') {
      parts.push('The overall mood trend shows improvement during this period.');
    } else if (data.mood.moodTrend === 'declining') {
      parts.push('The overall mood trend shows a decline during this period.');
    }
  }

  if (data.mood.morningAvg !== null && data.mood.eveningAvg !== null) {
    const diff = data.mood.eveningAvg - data.mood.morningAvg;
    if (Math.abs(diff) >= 1) {
      parts.push(
        diff > 0
          ? `Mood tends to improve throughout the day (morning: ${data.mood.morningAvg}, evening: ${data.mood.eveningAvg}).`
          : `Mood tends to decrease throughout the day (morning: ${data.mood.morningAvg}, evening: ${data.mood.eveningAvg}).`,
      );
    }
  }

  if (data.mood.topEmotions.length > 0) {
    const topNeg = data.mood.topEmotions.filter(e => e.category === 'negative').slice(0, 2);
    if (topNeg.length > 0) {
      parts.push(`The most frequently reported difficult emotions were ${topNeg.map(e => e.name.toLowerCase()).join(' and ')}.`);
    }
  }

  return parts.join(' ');
}
