#!/usr/bin/env tsx
/**
 * Emit src/config/categoryPosters.ts from the manifest's `wired` entries.
 * This is the wiring bridge: categoryService.getGrouped() reads CATEGORY_POSTERS
 * to set each card's `image`. Only wired entries are written, in concept order.
 *   tsx emit-config.ts
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { CONCEPTS } from './concepts.ts';
import { readManifest, REPO_ROOT } from './lib.ts';

function main() {
  const m = readManifest();
  const lines: string[] = [];
  let wired = 0;
  for (const c of CONCEPTS) {
    const e = m.entries[c.slug];
    if (e?.state === 'wired' && e.publicUrl) {
      lines.push(`  '${c.slug}': '${e.publicUrl}',`);
      wired++;
    }
  }

  const out = `/**
 * Category pictogram poster URLs (Supabase public storage), keyed by canonical
 * taxonomy slug. Wayfinding clay posters with the category name baked in.
 *
 * GENERATED by scripts/category-posters/emit-config.ts from
 * category_poster_manifest.json — do not edit by hand. Re-run the runner to
 * regenerate. categoryService.getGrouped() reads this to set each card's image.
 */
export const CATEGORY_POSTERS: Record<string, string> = {
${lines.join('\n')}
};
`;

  const dest = join(REPO_ROOT, 'src/config/categoryPosters.ts');
  writeFileSync(dest, out);
  console.log(`wrote ${dest} with ${wired} wired posters`);
}

main();
