/**
 * Share / Export utilities for Sleep Architect.
 *
 * - Share: encodes plan as base64 JSON in URL hash
 * - Export: copy summary to clipboard, download JSON, generate ICS
 */

import { SleepPlanInputs, SleepPlanOutput, formatDuration, parseTime, minutesBetween } from './model';

// ─── URL Share ──────────────────────────────────────────────────────────────

/** Encode plan inputs into a URL hash fragment */
export function encodePlanToHash(inputs: SleepPlanInputs): string {
  const compact = {
    b: inputs.bedtime,
    w: inputs.wakeTime,
    l: inputs.sleepLatencyMinutes,
    ac: inputs.awakeningsCount,
    am: inputs.awakeningMinutesEach,
    n: inputs.naps.map(n => ({ s: n.startTime, d: n.durationMinutes })),
    p: {
      a: inputs.profile.ageGroup,
      c: inputs.profile.chronotype,
      t: inputs.profile.targetSleepHours,
      cc: inputs.profile.caffeineCutoffTime,
      e: inputs.profile.exerciseTime,
    },
  };
  return btoa(JSON.stringify(compact));
}

/** Decode plan from URL hash fragment. Returns null if invalid. */
export function decodePlanFromHash(hash: string): SleepPlanInputs | null {
  try {
    const json = atob(hash);
    const c = JSON.parse(json);
    return {
      bedtime: c.b,
      wakeTime: c.w,
      sleepLatencyMinutes: c.l,
      awakeningsCount: c.ac,
      awakeningMinutesEach: c.am,
      naps: (c.n || []).map((n: { s: string; d: number }) => ({
        id: crypto.randomUUID(),
        startTime: n.s,
        durationMinutes: n.d,
      })),
      profile: {
        ageGroup: c.p.a,
        chronotype: c.p.c,
        targetSleepHours: c.p.t,
        caffeineCutoffTime: c.p.cc || '',
        exerciseTime: c.p.e || '',
      },
    };
  } catch {
    return null;
  }
}

/** Build a shareable URL with the plan encoded in the hash */
export function buildShareUrl(inputs: SleepPlanInputs): string {
  const hash = encodePlanToHash(inputs);
  const url = new URL(window.location.href.split('#')[0]);
  url.hash = `plan=${hash}`;
  return url.toString();
}

/** Try to extract plan from current URL hash */
export function extractPlanFromUrl(): SleepPlanInputs | null {
  const hash = window.location.hash;
  const match = hash.match(/^#plan=(.+)$/);
  if (!match) return null;
  return decodePlanFromHash(match[1]);
}

// ─── Export: Copy Summary ───────────────────────────────────────────────────

export function buildSummaryText(inputs: SleepPlanInputs, output: SleepPlanOutput): string {
  const lines = [
    '🌙 Sleep Architect — Plan Summary',
    '═══════════════════════════════════',
    '',
    `Bedtime:       ${inputs.bedtime}`,
    `Wake time:     ${inputs.wakeTime}`,
    `Latency:       ${inputs.sleepLatencyMinutes} min`,
    '',
    `Time in bed:   ${formatDuration(output.timeInBedMinutes)}`,
    `Total sleep:   ${formatDuration(output.totalSleepTimeMinutes)}`,
    `Efficiency:    ${Math.round(output.sleepEfficiency * 100)}%`,
    `Cycles:        ${output.estimatedCycles}`,
    '',
  ];

  if (output.wasoMinutes > 0) {
    lines.push(`WASO:          ${formatDuration(output.wasoMinutes)}`);
    lines.push('');
  }

  if (output.cycleArchitecture.length > 0) {
    lines.push('Cycle Breakdown:');
    output.cycleArchitecture.forEach(c => {
      lines.push(`  Cycle ${c.cycleNumber}: ${c.durationMinutes}min — N1 ${c.n1Percent}% | N2 ${c.n2Percent}% | N3 ${c.n3Percent}% | REM ${c.remPercent}%`);
    });
    lines.push('');
  }

  if (output.napAnalysis.length > 0) {
    lines.push('Naps:');
    output.napAnalysis.forEach(n => {
      lines.push(`  ${n.nap.startTime} (${n.nap.durationMinutes}min) — ${n.label}`);
    });
    lines.push('');
  }

  if (output.riskFlags.length > 0) {
    lines.push('Alerts:');
    output.riskFlags.forEach(f => {
      const icon = f.severity === 'danger' ? '🔴' : f.severity === 'warning' ? '🟡' : 'ℹ️';
      lines.push(`  ${icon} ${f.message}`);
    });
    lines.push('');
  }

  lines.push('Generated by Psychage Sleep Architect');
  lines.push('⚠ Not medical advice. Consult a healthcare provider for sleep disorders.');

  return lines.join('\n');
}

export async function copySummaryToClipboard(inputs: SleepPlanInputs, output: SleepPlanOutput): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(buildSummaryText(inputs, output));
    return true;
  } catch {
    return false;
  }
}

// ─── Export: JSON Download ──────────────────────────────────────────────────

export function downloadJson(inputs: SleepPlanInputs, output: SleepPlanOutput): void {
  const payload = {
    version: 1,
    exportedAt: new Date().toISOString(),
    inputs,
    results: {
      timeInBedMinutes: output.timeInBedMinutes,
      totalSleepTimeMinutes: output.totalSleepTimeMinutes,
      sleepEfficiency: output.sleepEfficiency,
      estimatedCycles: output.estimatedCycles,
      cycleArchitecture: output.cycleArchitecture,
      napAnalysis: output.napAnalysis.map(n => ({
        startTime: n.nap.startTime,
        durationMinutes: n.nap.durationMinutes,
        classification: n.classification,
        label: n.label,
      })),
      riskFlags: output.riskFlags,
    },
  };

  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `sleep-plan-${new Date().toISOString().slice(0, 10)}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Export: ICS Calendar ───────────────────────────────────────────────────

function toIcsDate(date: Date): string {
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

export function downloadIcs(inputs: SleepPlanInputs): void {
  const today = new Date();
  const yyyy = today.getFullYear();
  const mm = today.getMonth();
  const dd = today.getDate();

  const bedMin = parseTime(inputs.bedtime);
  const _wakeMin = parseTime(inputs.wakeTime);
  const tib = minutesBetween(inputs.bedtime, inputs.wakeTime);

  // Bedtime event — set to tonight
  const bedDate = new Date(yyyy, mm, dd, Math.floor(bedMin / 60), bedMin % 60);
  // If bedtime is after midnight, it's actually same day
  const wakeDate = new Date(bedDate.getTime() + tib * 60 * 1000);

  const events: string[] = [];

  // Main sleep event
  events.push([
    'BEGIN:VEVENT',
    `DTSTART:${toIcsDate(bedDate)}`,
    `DTEND:${toIcsDate(wakeDate)}`,
    `SUMMARY:Sleep — ${formatDuration(tib)}`,
    `DESCRIPTION:Bedtime ${inputs.bedtime} → Wake ${inputs.wakeTime}. Generated by Psychage Sleep Architect.`,
    `UID:sleep-${Date.now()}@psychage`,
    'END:VEVENT',
  ].join('\r\n'));

  // Nap events
  inputs.naps.forEach((nap, i) => {
    const napStart = parseTime(nap.startTime);
    const napDate = new Date(yyyy, mm, dd, Math.floor(napStart / 60), napStart % 60);
    const napEnd = new Date(napDate.getTime() + nap.durationMinutes * 60 * 1000);
    events.push([
      'BEGIN:VEVENT',
      `DTSTART:${toIcsDate(napDate)}`,
      `DTEND:${toIcsDate(napEnd)}`,
      `SUMMARY:Nap — ${nap.durationMinutes}min`,
      `DESCRIPTION:Scheduled nap. Generated by Psychage Sleep Architect.`,
      `UID:nap-${i}-${Date.now()}@psychage`,
      'END:VEVENT',
    ].join('\r\n'));
  });

  const ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Psychage//Sleep Architect//EN',
    ...events,
    'END:VCALENDAR',
  ].join('\r\n');

  const blob = new Blob([ics], { type: 'text/calendar' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `sleep-plan-${new Date().toISOString().slice(0, 10)}.ics`;
  a.click();
  URL.revokeObjectURL(url);
}
