/**
 * Category pictogram poster URLs (Supabase public storage), keyed by canonical
 * taxonomy slug. Wayfinding clay posters with the category name baked in.
 *
 * GENERATED by scripts/category-posters/emit-config.ts from
 * category_poster_manifest.json — do not edit by hand. Re-run the runner to
 * regenerate. categoryService.getGrouped() reads this to set each card's image.
 */
export const CATEGORY_POSTERS: Record<string, string> = {
  'anxiety-stress': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/anxiety-stress.jpeg',
  'depression-grief': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/depression-grief.jpeg',
  'trauma-healing': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/trauma-healing.jpeg',
  'mental-health-conditions': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/mental-health-conditions.jpeg',
  'psychosis-schizophrenia': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/psychosis-schizophrenia.jpeg',
  'neurodivergence-adhd-autism': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/neurodivergence-adhd-autism.jpeg',
  'eating-body': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/eating-body.jpeg',
  'chronic-illness-pain': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/chronic-illness-pain.jpeg',
  'aging-dementia-late-life': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/aging-dementia-late-life.jpeg',
  'emotional-regulation': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/emotional-regulation.jpeg',
  'habits-behavior-change': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/habits-behavior-change.jpeg',
  'sleep-body-connection': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/sleep-body-connection.jpeg',
  'self-worth-identity': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/self-worth-identity.jpeg',
  'therapy-navigation': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/therapy-navigation.jpeg',
  'creativity-therapeutic-arts': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/creativity-therapeutic-arts.jpeg',
  'life-skills-practical-psychology': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/life-skills-practical-psychology.jpeg',
  'sports-exercise-psychology': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/sports-exercise-psychology.jpeg',
  'relationships-communication': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/relationships-communication.jpeg',
  'work-productivity': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/work-productivity.jpeg',
  'loneliness-connection': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/loneliness-connection.jpeg',
  'digital-life': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/digital-life.jpeg',
  'technology-digital-life': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/technology-digital-life.jpeg',
  'cultural-global': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/cultural-global.jpeg',
  'womens-mental-health': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/womens-mental-health.jpeg',
  'mens-mental-health': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/mens-mental-health.jpeg',
  'environmental-eco-psychology': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/environmental-eco-psychology.jpeg',
  'spirituality-meaning': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/spirituality-meaning.jpeg',
  'financial-wellness': 'https://ozourhqyqtpppvpbhphw.supabase.co/storage/v1/object/public/article-images/category-covers/financial-wellness.jpeg',
};
