#!/usr/bin/env tsx
/**
 * Promote article TSX records from status:'draft' to status:'published'
 * for every article whose prose word count clears the 1,500-word quality bar.
 *
 * Input: scripts/prose-word-count-results.json (generated by count-prose-words.cjs)
 * Effect: in-place edits to src/data/articles/category-*\/*.tsx
 *
 * Run dry-run first:
 *   node scripts/count-prose-words.cjs
 *   npx tsx scripts/promote-quality-articles.ts
 *
 * Then apply:
 *   npx tsx scripts/promote-quality-articles.ts --apply
 *
 * Idempotent. Only replaces `status: 'draft'` inside the object literal that
 * contains the target slug. If an article's status has already been promoted,
 * or is 'archived'/something-else, it's skipped.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const WORD_THRESHOLD = 1500;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const RESULTS_PATH = path.join(REPO_ROOT, 'scripts', 'prose-word-count-results.json');
const ARTICLES_DIR = path.join(REPO_ROOT, 'src', 'data', 'articles');

interface WordCountEntry {
    file: string;       // relative to ARTICLES_DIR, e.g. "category-13/02b-mood-disorders.tsx"
    title: string;
    slug: string;
    wordCount: number;
}

interface WordCountResults {
    summary: Record<string, unknown>;
    articles: WordCountEntry[];
}

interface PromotionOutcome {
    file: string;
    slug: string;
    wordCount: number;
    status: 'promoted' | 'already_published' | 'not_found' | 'non_draft_status' | 'ambiguous';
    details?: string;
}

function escapeRegex(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Promote a single article's status in file content.
 *
 * Matches `status: 'draft'` that appears within 500 characters after the
 * `slug: '<SLUG>'` occurrence AND before the next `slug:` occurrence (so we
 * stay inside the target article's object literal).
 */
function promoteArticleInSource(
    source: string,
    slug: string,
): { updated: string; outcome: PromotionOutcome['status']; details?: string } {
    const escSlug = escapeRegex(slug);
    const slugRe = new RegExp(`slug:\\s*['"\`]${escSlug}['"\`]`, 'g');
    const slugMatches: RegExpExecArray[] = [];
    let m: RegExpExecArray | null;
    while ((m = slugRe.exec(source)) !== null) slugMatches.push(m);

    if (slugMatches.length === 0) {
        return { updated: source, outcome: 'not_found' };
    }
    if (slugMatches.length > 1) {
        return { updated: source, outcome: 'ambiguous', details: `${slugMatches.length} slug matches` };
    }

    const slugMatch = slugMatches[0];
    const slugStart = slugMatch.index;

    // Find the next `slug:` after this one (or end of file) to bound the search window.
    const afterSlug = source.slice(slugStart + slugMatch[0].length);
    const nextSlugMatch = afterSlug.search(/slug:\s*['"`]/);
    const searchWindowEnd = slugStart + slugMatch[0].length + (nextSlugMatch === -1 ? afterSlug.length : nextSlugMatch);

    // Also respect an explicit 500-char proximity cap — articles rarely space
    // status so far from slug that we'd need more.
    const windowEnd = Math.min(slugStart + slugMatch[0].length + 500, searchWindowEnd);
    const window = source.slice(slugStart, windowEnd);

    const statusRe = /status:\s*(['"`])(draft|published|archived|review)\1/;
    const statusMatch = window.match(statusRe);

    if (!statusMatch) {
        // No explicit status field next to slug. Could be inline article with status
        // placed before slug in its object literal — check 500 chars before slug too.
        const windowStart = Math.max(0, slugStart - 500);
        // Bound backwards: stop at previous slug or array start
        const before = source.slice(windowStart, slugStart);
        const prevSlugIdx = before.search(/slug:\s*['"`][^'"`]+['"`][^]*$/);
        const effectiveBeforeStart = windowStart + (prevSlugIdx === -1 ? 0 : prevSlugIdx);
        const beforeWindow = source.slice(effectiveBeforeStart, slugStart);
        const beforeStatusMatch = beforeWindow.match(statusRe);
        if (!beforeStatusMatch) {
            return { updated: source, outcome: 'not_found', details: 'no status field near slug' };
        }
        const value = beforeStatusMatch[2];
        if (value === 'published') return { updated: source, outcome: 'already_published' };
        if (value !== 'draft') return { updated: source, outcome: 'non_draft_status', details: `status='${value}'` };

        const absIdx = effectiveBeforeStart + (beforeStatusMatch.index ?? 0);
        const before2 = source.slice(0, absIdx);
        const matched = beforeStatusMatch[0];
        const quote = beforeStatusMatch[1];
        const replaced = `status: ${quote}published${quote}`;
        const after2 = source.slice(absIdx + matched.length);
        return { updated: before2 + replaced + after2, outcome: 'promoted' };
    }

    const value = statusMatch[2];
    if (value === 'published') return { updated: source, outcome: 'already_published' };
    if (value !== 'draft') return { updated: source, outcome: 'non_draft_status', details: `status='${value}'` };

    const absIdx = slugStart + (statusMatch.index ?? 0);
    const matched = statusMatch[0];
    const quote = statusMatch[1];
    const replaced = `status: ${quote}published${quote}`;

    const updated = source.slice(0, absIdx) + replaced + source.slice(absIdx + matched.length);
    return { updated, outcome: 'promoted' };
}

function categoryScopeMode(apply: boolean, categoryNum: number) {
    const catDir = path.join(ARTICLES_DIR, `category-${String(categoryNum).padStart(2, '0')}`);
    if (!fs.existsSync(catDir)) {
        console.error(`❌ Category directory not found: ${catDir}`);
        process.exit(1);
    }

    console.log(`\n${apply ? '🔧 APPLY MODE' : '🔍 DRY RUN'} — promote-quality-articles --category ${categoryNum}`);
    console.log('='.repeat(100));
    console.log(`Scope: every status:'draft' in ${path.relative(REPO_ROOT, catDir)}/*.tsx`);
    console.log(`Word-count threshold: IGNORED (category-scope mode)\n`);

    const files = fs.readdirSync(catDir).filter(
        f => f.endsWith('.tsx') && !['_shared.tsx', 'index.tsx', '_shared.ts', 'index.ts'].includes(f),
    );

    let totalPromoted = 0;
    let filesChanged = 0;
    const perFile: { file: string; promoted: number }[] = [];

    const draftRe = /status:\s*(['"`])draft\1/g;

    for (const f of files.sort()) {
        const abs = path.join(catDir, f);
        const source = fs.readFileSync(abs, 'utf-8');
        const matches = source.match(draftRe) || [];
        if (matches.length === 0) {
            perFile.push({ file: f, promoted: 0 });
            continue;
        }
        const updated = source.replace(draftRe, (_match, quote) => `status: ${quote}published${quote}`);
        if (apply && updated !== source) {
            fs.writeFileSync(abs, updated, 'utf-8');
        }
        totalPromoted += matches.length;
        if (updated !== source) filesChanged++;
        perFile.push({ file: f, promoted: matches.length });
    }

    console.log('PER-FILE RESULTS');
    console.log('-'.repeat(100));
    for (const p of perFile) {
        console.log(`  ${String(p.promoted).padStart(3)} promoted | ${p.file}`);
    }

    console.log('-'.repeat(100));
    console.log(`Total: ${totalPromoted} articles promoted across ${filesChanged} files`);

    if (!apply) {
        console.log('\n💡 Re-run with --apply to actually write changes.');
    } else {
        console.log('\n✅ Changes written. Run `npm run lint` and `npm run build` to verify.');
    }
}

function allDraftsMode(apply: boolean) {
    console.log(`\n${apply ? '🔧 APPLY MODE' : '🔍 DRY RUN'} — promote-quality-articles --all-drafts`);
    console.log('='.repeat(100));
    console.log(`Scope: every status:'draft' across ALL category-*\/*.tsx files`);
    console.log(`Word-count threshold: IGNORED\n`);

    const draftRe = /status:\s*(['"`])draft\1/g;
    const cats = fs.readdirSync(ARTICLES_DIR)
        .filter(d => d.startsWith('category-') && fs.statSync(path.join(ARTICLES_DIR, d)).isDirectory())
        .sort();

    let totalPromoted = 0;
    let filesChanged = 0;
    const perCat: { cat: string; promoted: number; filesTouched: number }[] = [];

    for (const cat of cats) {
        const dir = path.join(ARTICLES_DIR, cat);
        const files = fs.readdirSync(dir).filter(
            f => f.endsWith('.tsx') && !['_shared.tsx', 'index.tsx', '_shared.ts', 'index.ts'].includes(f),
        );
        let catPromoted = 0;
        let catFilesTouched = 0;
        for (const f of files) {
            const abs = path.join(dir, f);
            const source = fs.readFileSync(abs, 'utf-8');
            const matches = source.match(draftRe) || [];
            if (matches.length === 0) continue;
            const updated = source.replace(draftRe, (_match, quote) => `status: ${quote}published${quote}`);
            if (apply && updated !== source) fs.writeFileSync(abs, updated, 'utf-8');
            catPromoted += matches.length;
            if (updated !== source) catFilesTouched++;
        }
        if (catPromoted > 0) perCat.push({ cat, promoted: catPromoted, filesTouched: catFilesTouched });
        totalPromoted += catPromoted;
        filesChanged += catFilesTouched;
    }

    console.log('PER-CATEGORY RESULTS');
    console.log('-'.repeat(100));
    for (const p of perCat) {
        console.log(`  ${String(p.promoted).padStart(4)} promoted across ${String(p.filesTouched).padStart(2)} files | ${p.cat}`);
    }
    console.log('-'.repeat(100));
    console.log(`Total: ${totalPromoted} articles promoted across ${filesChanged} files`);

    if (!apply) console.log('\n💡 Re-run with --apply to actually write changes.');
    else console.log('\n✅ Changes written. Run `npm run build` to verify.');
}

async function main() {
    const apply = process.argv.includes('--apply');

    if (process.argv.includes('--all-drafts')) {
        allDraftsMode(apply);
        return;
    }

    const catIdx = process.argv.indexOf('--category');
    if (catIdx !== -1 && catIdx + 1 < process.argv.length) {
        const catNum = parseInt(process.argv[catIdx + 1], 10);
        if (Number.isNaN(catNum)) {
            console.error('❌ --category requires a number, e.g., --category 13');
            process.exit(1);
        }
        categoryScopeMode(apply, catNum);
        return;
    }

    if (!fs.existsSync(RESULTS_PATH)) {
        console.error(`❌ Missing ${RESULTS_PATH}`);
        console.error('   Run: node scripts/count-prose-words.cjs');
        process.exit(1);
    }

    const results: WordCountResults = JSON.parse(fs.readFileSync(RESULTS_PATH, 'utf-8'));
    const candidates = results.articles.filter(a => a.wordCount >= WORD_THRESHOLD);

    // Group by file
    const byFile = new Map<string, WordCountEntry[]>();
    for (const a of candidates) {
        if (!byFile.has(a.file)) byFile.set(a.file, []);
        byFile.get(a.file)!.push(a);
    }

    console.log(`\n${apply ? '🔧 APPLY MODE' : '🔍 DRY RUN'} — promote-quality-articles`);
    console.log('='.repeat(100));
    console.log(`Threshold: ${WORD_THRESHOLD} words`);
    console.log(`Candidates: ${candidates.length} articles across ${byFile.size} files\n`);

    const outcomes: PromotionOutcome[] = [];
    let filesChanged = 0;

    for (const [relFile, articles] of [...byFile.entries()].sort()) {
        const absPath = path.join(ARTICLES_DIR, relFile);
        if (!fs.existsSync(absPath)) {
            for (const a of articles) outcomes.push({ file: relFile, slug: a.slug, wordCount: a.wordCount, status: 'not_found', details: 'file missing' });
            continue;
        }

        let source = fs.readFileSync(absPath, 'utf-8');
        const originalSource = source;

        for (const a of articles) {
            const result = promoteArticleInSource(source, a.slug);
            outcomes.push({ file: relFile, slug: a.slug, wordCount: a.wordCount, status: result.outcome, details: result.details });
            source = result.updated;
        }

        if (source !== originalSource) {
            filesChanged++;
            if (apply) {
                fs.writeFileSync(absPath, source, 'utf-8');
            }
        }
    }

    // Report
    const counts = {
        promoted: 0,
        already_published: 0,
        not_found: 0,
        non_draft_status: 0,
        ambiguous: 0,
    };
    for (const o of outcomes) counts[o.status]++;

    console.log('OUTCOMES');
    console.log('-'.repeat(100));
    console.log(`  ✅ Promoted (draft → published):   ${counts.promoted}`);
    console.log(`  ⏭  Already published (no-op):      ${counts.already_published}`);
    console.log(`  ⚠  Non-draft status (left alone):  ${counts.non_draft_status}`);
    console.log(`  ❓ Status field not found:         ${counts.not_found}`);
    console.log(`  ⚠  Ambiguous (multiple matches):   ${counts.ambiguous}`);
    console.log(`\nFiles ${apply ? 'written' : 'that would be written'}: ${filesChanged}`);

    if (counts.not_found > 0 || counts.ambiguous > 0) {
        console.log('\nPROBLEM CASES (need manual review):');
        console.log('-'.repeat(100));
        for (const o of outcomes) {
            if (o.status === 'not_found' || o.status === 'ambiguous') {
                console.log(`  [${o.status}] ${o.file} :: ${o.slug}${o.details ? ` (${o.details})` : ''}`);
            }
        }
    }

    if (counts.non_draft_status > 0) {
        console.log('\nNON-DRAFT STATUSES ENCOUNTERED:');
        console.log('-'.repeat(100));
        for (const o of outcomes) {
            if (o.status === 'non_draft_status') {
                console.log(`  ${o.file} :: ${o.slug} (${o.details})`);
            }
        }
    }

    if (counts.promoted > 0) {
        console.log('\nSAMPLE PROMOTIONS (first 10):');
        console.log('-'.repeat(100));
        const promotions = outcomes.filter(o => o.status === 'promoted').slice(0, 10);
        for (const o of promotions) {
            console.log(`  ${String(o.wordCount).padStart(5)}w | ${o.file} :: ${o.slug}`);
        }
    }

    if (!apply) {
        console.log('\n💡 Re-run with --apply to actually write changes.');
    } else {
        console.log('\n✅ Changes written. Run `npm run lint` and `npm run build` to verify.');
    }
}

main().catch(err => {
    console.error(err);
    process.exit(1);
});
